config/routes.rb
Rails.application.routes.draw do
  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'

  
  resources :orders do
    resources :orderitems # when create an order will allow us to push the order items into the order and store 
  end

  devise_for :users do
    resources:orders # nesting resources like above so user has access 
  end
 
  get '/checkout' => 'cart#createOrder'
 
  post '/search' => 'items#search'
    
  get 'cart/index'
  resources :items
  root 'static_pages#home'

  
  get '/about' => 'static_pages#about' 
  get '/account' => 'static_pages#account'
  
  resources :categories
  get 'category/:title', to: 'static_pages#category'
  
  
  get '/cart/clear' => 'cart#clearCart'
  
  get '/cart/:id' => 'cart#add'#when user clicks add to cart button -get cart item id(created by rails) and go to cart controller use add method
  
  get '/cart/remove/:id' => 'cart#remove'
  
 
  get '/paid/:id' => 'static_pages#paid'
  
  get '/cart/decrease/:id' => 'cart#decrease'
  get '/cart/increase/:id' => 'cart#increase'
  get '/cart' => 'cart#index'

  #get 'static_pages/home'

  #get 'static_pages/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_adminNav.html.erb
<a href="#" class="open">&equiv;</a>
<a href="#" class="close hidden">&times;</a>

<nav id="admin">
    <div class="line"></div>
    <a class="links"><%= link_to "Home", "/" %></a>
    <div class="line"></div>
    <a class="links"><%= link_to "Shop +", "/items" %></a>
    <div class="line"></div>
    <%=render 'layouts/categories'%>
    <div class="line"></div>
    <a class="links"><%= link_to "About Us", about_path %></a>
    <div class="line"></div>
    <a class="links"><%= link_to "Account", account_path %></a>
    <div class="line"></div>
    <a><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></a><!--built in devise commands-->
    <div class="line"></div>
    <a class="links">Admin +</a>
    <%= link_to 'Add Item',  new_item_path, :class => "cats", :role => "cats" %>
    <%= link_to 'Edit Categories', categories_path, :class =>"cats", :role=>"cats"  %>
    <%= link_to "Members Orders", "/orders", :class =>"cats", :role=>"cats" %>
    <div class="line"></div>
    <div class="line"></div>
    <br><br><br>
    <%= render 'layouts/search' %> 
    <br><br>
    <p>Workshop.&copy; 2019</p>
    <hr/>
</nav>

<div id = "header">
    <%= link_to "Workshop", "/" %>
</div>  

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_nav.html.erb
<div class="fixed"><!--hamburger -->
    <a href="#" class="open">&equiv;</a>
    <a href="#" class="close hidden">&times;</a>
</div> 

<nav><!--SIDE BAR -->
    <a class="links"><%= link_to "Cart", "/cart" %></a>
    <div class="line"></div>
    <a class="links"><%= link_to "Home", "/" %></a>
    <div class="line"></div>
    <a class="links"><%= link_to "Shop +", "/items" %></a>
    <div class="line"></div>
    <%=render 'layouts/categories'%> 
    <div class="line"></div>
    <a class="links"><%= link_to "About Us", about_path %></a>
    <div class="line"></div>
    
    <% if user_signed_in? %>  <!--MEMBER NAV-->
        <a class="links"><%= link_to "Account", account_path %></a>
        <div class="line"></div>
        <a><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></a><!--built in devise commands-->
    <% else %> 
        <a><%= link_to 'Log in', new_user_session_path %></a><!-- devise is built around sessions like the cart -->
        <a><%= link_to 'Create Account', new_user_registration_path %></a>
    <% end %>
    
    <% if user_signed_in? && current_user.admin %>  <!--ADMIN NAV-->
        <a class="links">Admin +</a>
        <%= link_to 'Add Item',  new_item_path, :class => "cats", :role => "cats" %>
        <%= link_to 'Edit Categories', categories_path, :class =>"cats", :role=>"cats"  %>
        <%= link_to "Members Orders", "/orders", :class =>"cats", :role=>"cats" %>
        <div class="line"></div>
    <% end %><br><br><br> <!--end devise set up-->
    
    <%= render 'layouts/search' %><br><br>
    <p>Workshop.&copy; 2019</p><hr/>
  
</nav>

<div id="header">
    <a><%= link_to "Workshop", "/" %></a> 
</div>


 