config/routes.rb
Rails.application.routes.draw do
  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'

  
  resources :orders do
    resources :orderitems # when create an order will allow us to push the order items into the order and store 
  end

  devise_for :users do
    resources:orders # nesting resources like above so user has access 
  end
 
  get '/checkout' => 'cart#createOrder'
 
  post '/search' => 'items#search'
    
  get 'cart/index'
  resources :items
  root 'static_pages#home'

  
  get '/about' => 'static_pages#about' 
  get '/account' => 'static_pages#account'
  
  resources :categories
  get 'category/:title', to: 'static_pages#category'
  
  
  get '/cart/clear' => 'cart#clearCart'
  
  get '/cart/:id' => 'cart#add'#when user clicks add to cart button -get cart item id(created by rails) and go to cart controller use add method
  
  get '/cart/remove/:id' => 'cart#remove'
  
 
  get '/paid/:id' => 'static_pages#paid'
  
  get '/cart/decrease/:id' => 'cart#decrease'
  get '/cart/increase/:id' => 'cart#increase'
  get '/cart' => 'cart#index'

  #get 'static_pages/home'

  #get 'static_pages/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [ :show,:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    #@categories = Category.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
   @items = Item.all
   # @categories = Category.all
  end

  # GET /items/new
  def new
  #  @categories = Category.all
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  #  @categories = Category.all
  end

  # POST /items
  # POST /items.json
  def create
  #  @categories = Category.all
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def search
    searchterm = "%#{params[:searchbox]}%" # var searchterm = searchbox input
    @items = Item.where("title like ?", searchterm) #instance var items = items where the title is like searchterm(users input)
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :brand, :category, :image_url)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form"> <!--form wrapper -->

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>

    <div class="field">
      <%= f.label :price %>
      <%= f.text_field :price %>
    </div>

    <div class="field">
      <%= f.label :brand %>
      <%= f.text_field :brand %>
    </div>

    <div class="field">
      <%= f.label :category %>
      <%= f.text_field :category %>
    </div>

    <div class="field">
      <%= f.label :image_url %>
      <%= f.text_field :image_url, placeholder: 'Type image_url here', id: "imageInput", oninput: "textChanged()", required: true %>
    </div>
    
    <p id="feedback"></p>
    
    <div class="actions">
      <%= f.submit %>
    </div>
    
  </div> <!--end form wrapper -->
  
<% end %>

app/views/items/edit.html.erb
<% provide(:title, "Edit Item")%>

<div class= "main">
    <h2 class="title">Edit Item</h2>
    <%= render 'form', item: @item %>
    <%= link_to 'Show', @item %> |
    <%= link_to 'Back', items_path %>
</div> 

app/views/items/index.html.erb
<% provide(:title, "Create Shop") %>
<p id="notice"><%= notice %></p>

<div class="wrap"><h2 class="underline">ALL</h2></div>

<div class="card-container">
   <% @items.each do |item| %>
       <div class="card">
           <h3><%= item.title %></h3>
           <%= link_to (image_tag item.image_url, :class => "card-img"), item %>
       
           <div class="card-body"></div>
           <p><%=  item.description %></p>
           <p>Price <%= number_to_currency(item.price, :unit => "€") %><br>
               Brand: <%= item.brand %><br>
               Category: <%= item.category %></p><br>
            <p>
                <!-- link_to 'Show',  item, :class => "link", :role => "link" -->
                <a href="/cart/<%= item.id %>" class="buttonWhite">Add To Cart</a>
                <% if user_signed_in? && current_user.admin %>
                     <%= link_to 'Edit',  edit_item_path(item), :class => "buttonWhite", :role => "link" %>
                     <%= link_to 'Destroy',  item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "buttonWhite", :role => "link" %>
                 <% end %>
            </p>
        </div> <!-- end card -->
    <% end %>
</div><br> <!-- end card-container -->

<% if user_signed_in? && current_user.admin %>
  <div class="main">
    <%= link_to 'New Item',  new_item_path, :class => "button", :role => "link" %>
  </div>
<% end %>

app/views/items/new.html.erb
<% provide(:title, "New Item")%>

<div class= "main">
    <h2 class="title">New Item</h2>
    <%= render 'form', item: @item %>
    <%= link_to 'Back', items_path %>
</div> 

app/views/items/search.html.erb
<div><h2>Were you looking for something?</h2></div><br><br>

<% provide(:title, "Create Shop") %>
<p id="notice"><%= notice %></p>
<h2 class="welcome"></h2>
<div id="itemCounter">
  <!--P tag will be placed in here by-->
</div>
  
<div class="card-container">
  <% @items.each do |item| %>
    <div class="card">
       <h3><%= item.title %></h3>
       <%= link_to (image_tag item.image_url, :class => "card-img"), item %>
       <div class="card-body"></div>
       <p><%=  item.description %></p>
       <p>Price <%= number_to_currency(item.price, :unit => "€") %><br>
           Brand: <%= item.brand %><br>
           Category: <%= item.category %>
       </p><br>
       
       <p>
         <%= link_to 'Show',  item, :class => "link", :role => "link" %>
         <a href="/cart/<%= item.id %>" class="link">Add To Cart</a>
 
         <% if session[:login] == 1 %>
           <%= link_to 'Edit',  edit_item_path(item), :class => "link", :role => "link" %>
           <%= link_to 'Destroy',  item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "link", :role => "link" %>
         <% end %>
       </p>
       
     </div>
  <% end %>
</div><br>


<script>

 /* Keeps count of Items created */
 function setItemCount() {
   var items = $('.card');
   var numberOfPhones = items.length;
   var phoneCounter = document.getElementById("itemCounter");
   phoneCounter.innerHTML = "<p>Your search result has returned '" + numberOfPhones + "'</p>";
  
 }
 
 setItemCount();

</script>

app/views/items/show.html.erb
<div class ="body-container">
  
  <div style ="padding-top: 8%" class="card">
    <h3><%= @item.title %></h3>
    <h3><%= @item.brand %></h3>
    <div class="underline"></div>
    <h5>€<%=  @item.price %></h5>
    <div class="underline"></div> 
    <p><%= @item.description %></p><p>  <%= @item.category %></p>
    <a href="/cart/<%= @item.id %>" class="button">Add To Cart</a>
  </div>
  
  <div class="card">
    <div class="card-img"><%=  image_tag(@item.image_url) %> </div> 
  </div>
  
</div>

<% if user_signed_in? && current_user.admin %>
  <%= link_to 'Edit', edit_item_path(@item), :class => "buttonWhite"%> 
<% end %>
         
<%= link_to 'Back', items_path %>